# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: enffl2341502
  host: localhost

development:
  <<: *default
  database: junmannn_development

test:
  <<: *default
  database: junmannn_test

production:
  <<: *default
  database: junmannn_production
  username: <YOUR_PRODUCTION_USERNAME>
  password: <YOUR_PRODUCTION_PASSWORD>
  host: <YOUR_PRODUCTION_HOST>
